version: 2
jobs:
  build-windows-linux:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: yarn && yarn release --win --linux

  build-macos:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: yarn && yarn release --mac

workflows:
  version: 2
  build:
    jobs:
      - build-windows
      - build-windows-linux
